import { useState } from 'react';
import Barcode from 'react-barcode';
import { X, Printer } from 'lucide-react';
import { formatCurrency } from '../../utils/helpers';

export default function BarcodePrintModal({ product, onClose }) {
  const [copies, setCopies] = useState(1);
  const [labelSize, setLabelSize] = useState('50x25');

  // Generate fallback barcode if none exists (just use SKU or ID)
  const barcodeValue = product.barcode || product.sku || product.id.substring(0, 8).toUpperCase();

  const handlePrint = () => {
    // Get the SVG element generated by react-barcode
    const barcodeSvg = document.getElementById('barcode-svg-container').innerHTML;

    const printWindow = document.createElement('iframe');
    printWindow.style.position = 'absolute';
    printWindow.style.top = '-1000px';
    document.body.appendChild(printWindow);

    let labelsHTML = '';
    for (let i = 0; i < copies; i++) {
      labelsHTML += `
        <div class="label">
          <div class="product-name">${product.name}</div>
          <div class="barcode-wrapper">${barcodeSvg}</div>
          <div class="price">${formatCurrency(product.price)}</div>
        </div>
      `;
    }

    // CSS based on label size
    let pageCss = '';
    if (labelSize === '50x25') {
      pageCss = `@page { size: 50mm 25mm; margin: 0; } .label { width: 50mm; height: 25mm; padding: 1mm; }`;
    } else if (labelSize === '80x40') {
      pageCss = `@page { size: 80mm 40mm; margin: 0; } .label { width: 80mm; height: 40mm; padding: 2mm; } .product-name { font-size: 14px !important; } .price { font-size: 16px !important; }`;
    }

    const html = `
      <html>
      <head>
        <title>Print Barcodes</title>
        <style>
          ${pageCss}
          body { 
            margin: 0; padding: 0; background: white; 
            font-family: Arial, sans-serif;
          }
          .label { 
            display: flex; flex-direction: column; align-items: center; justify-content: center; 
            page-break-after: always; 
            box-sizing: border-box;
            overflow: hidden;
          }
          .label:last-child { page-break-after: auto; }
          .product-name { 
            font-size: 10px; font-weight: bold; margin-bottom: 2px; text-align: center; 
            white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 95%; 
          }
          .price { 
            font-size: 12px; font-weight: 800; margin-top: 2px; 
          }
          .barcode-wrapper {
            display: flex; justify-content: center; align-items: center; width: 100%; flex: 1; min-height: 0;
          }
          .barcode-wrapper svg {
            max-width: 100%; max-height: 100%; height: auto; display: block;
          }
        </style>
      </head>
      <body>
        ${labelsHTML}
      </body>
      </html>
    `;

    printWindow.contentDocument.open();
    printWindow.contentDocument.write(html);
    printWindow.contentDocument.close();

    printWindow.onload = () => {
      printWindow.contentWindow.focus();
      printWindow.contentWindow.print();
      setTimeout(() => document.body.removeChild(printWindow), 500);
    };
  };

  return (
    <div className="overlay" onClick={onClose}>
      <div className="modal animate-scale-in" onClick={e => e.stopPropagation()} style={{ width: '100%', maxWidth: 400, padding: 0 }}>
        <div style={{ padding: '20px 24px', borderBottom: '1px solid var(--color-border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <h2 style={{ fontSize: 18, fontWeight: 700 }}>Print Barcodes</h2>
          <button onClick={onClose} className="btn btn-ghost btn-icon" style={{ minWidth: 36, minHeight: 36, padding: 0 }}>
            <X size={18} />
          </button>
        </div>

        <div style={{ padding: 24, display: 'flex', flexDirection: 'column', gap: 20 }}>
          {/* Settings */}
          <div style={{ display: 'flex', gap: 12 }}>
            <div style={{ flex: 1 }}>
              <label style={{ fontSize: 13, fontWeight: 600, display: 'block', marginBottom: 6 }}>Copies</label>
              <input
                type="number"
                className="input"
                value={copies}
                onChange={e => setCopies(Math.max(1, parseInt(e.target.value) || 1))}
                min="1"
              />
            </div>
            <div style={{ flex: 1 }}>
              <label style={{ fontSize: 13, fontWeight: 600, display: 'block', marginBottom: 6 }}>Label Size</label>
              <select className="input" value={labelSize} onChange={e => setLabelSize(e.target.value)}>
                <option value="50x25">50mm x 25mm</option>
                <option value="60x40">60mm x 40mm</option>
                <option value="80x40">80mm x 40mm</option>
              </select>
            </div>
          </div>

          {/* Preview Container */}
          <div>
            <label style={{ fontSize: 13, fontWeight: 600, display: 'block', marginBottom: 6 }}>Preview</label>
            <div style={{
              background: 'white', border: '1px dashed var(--color-border)', borderRadius: 'var(--radius-md)',
              padding: 16, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center'
            }}>
              <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 4, color: 'black' }}>{product.name}</div>

              {/* Hidden container just to extract SVG */}
              <div id="barcode-svg-container">
                <Barcode
                  value={barcodeValue}
                  width={1.5}
                  height={40}
                  fontSize={12}
                  margin={0}
                  displayValue={true}
                  background="#ffffff"
                  lineColor="#000000"
                />
              </div>

              <div style={{ fontSize: 16, fontWeight: 800, marginTop: 4, color: 'black' }}>{formatCurrency(product.price)}</div>
            </div>
          </div>

          {/* Alert if no barcode */}
          {!product.barcode && (
            <div style={{ padding: 12, background: 'var(--color-warning-light)', color: '#92400e', borderRadius: 'var(--radius-sm)', fontSize: 12 }}>
              <strong>Note:</strong> This product doesn't have a specific barcode assigned. Generating one using its SKU or ID.
            </div>
          )}

          <button className="btn btn-primary btn-lg" onClick={handlePrint} style={{ width: '100%' }}>
            <Printer size={18} /> Print {copies} Labels
          </button>
        </div>
      </div>
    </div>
  );
}
